import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { QueryProvider } from "@/provider/query-provider";

const poppins = Poppins({
  weight: ["100","200","300","400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession(authOptions)

  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          {/* <AuthProvider session={session}> */}
          <main>{children}</main>
          {/* </AuthProvider> */}
        </QueryProvider>
      </body>
    </html>
  );
}
